### PR TITLE
Update Header styles

### LINKED ISSUE #260: Menu bar style colors change
We want to come close to this
image

Figma: https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?node-id=839%3A27689&mode=dev

This is for:
- changing the logo. Use this: 
MULTIX_LOGO_FULL_BLUE_1200px
- changing the font weigth of the menu
- changing the background for the right gray

### PR DESCRIPTION
**Pull request by Lykhoyda**
Closes #260 

- Updated navbar background
- logo update
- fix navbar elements to jump to the next line
- fix colors, hover
- renamed Header component

updates:
- Fixed the gray background color of the page
- Logo color
- Watch the account navigation link for ConnectOrWatch component

### CODE REVIEW

**Review by Tbaut — CHANGES_REQUESTED** [review]
- The background of the main app is `#FAFCFD` afaics from the design. Only the menu (and some components are `#fff` or `white` also on this, it's quite rare in design to use pure white/black. Let me catch up on that with Cindy. In the mean time, we can use white/black cf https://graphicdesign.stackexchange.com/questions/25356/why-not-use-pure-black-000-and-pure-white-fff

- Some elements like a loader are invisible now, there's a loader there usually. I believe it is https://github.com/ChainSafe/Multix/blob/ec101c7dfebe29a2c30e78b84f11ee094feac17e/packages/ui/src/components/select/MultiProxySelection.tsx#L152
image


- Having a scrollbar and the dropdown for Networks cut is worse than having the menu on 2 lines IMHO. We should implement this only after https://github.com/ChainSafe/Multix/issues/264

image

- Let's try not to use `black` or `white` in the code directly, and rather use the theme.palette colors so that we can change them quickly.

**Comment by Lykhoyda** [comment]
> * The background of the main app is `#FAFCFD` afaics from the design. Only the menu (and some components are `#fff` or `white` also on this, it's quite rare in design to use pure white/black. Let me catch up on that with Cindy. In the mean time, we can use white/black cf https://graphicdesign.stackexchange.com/questions/25356/why-not-use-pure-black-000-and-pure-white-fff
> * Some elements like a loader are invisible now, there's a loader there usually. I believe it is https://github.com/ChainSafe/Multix/blob/ec101c7dfebe29a2c30e78b84f11ee094feac17e/packages/ui/src/components/select/MultiProxySelection.tsx#L152
>   
>   image
> * Having a horizontal scrollbar and the dropdown for Networks cut is worse than having the menu on 2 lines IMHO. We should implement this only after [Rework the network dropdown #264](https://github.com/ChainSafe/Multix/issues/264)
>   image
> * Let's try not to use `black` or `white` in the code directly, and rather use the theme.palette colors so that we can change them quickly.

The background color is probably not updated everywhere, please provide the link next time if there is a original version of the design.
2) I agree that is not ideal, but as I said it shouldn't affect the users as screen size is not common. Let's have 2 lines if it's "better" 😃

**Comment by Tbaut** [comment]
> The background color is probably not updated everywhere, please provide the link next time

The link is in the original issue, pointing to a figma node that has been deleted in the mean time... Feel free to ask then. However the figma with this view is still there, and the screenshot in the original issue is also quite clear. On top of this there's a mention of "updating the background to the right gray". Doing my best to have well scoped issues, but at some point you gotta help too :)

**Review by Tbaut — APPROVED** [review]
Looking great thanks a lot!

**Pull request merged**
