### PR TITLE
update buttons and links

### LINKED ISSUE #200: Update all buttons design in the project
Scenario: All the buttons and links components should be updated with the new UI component from #189 
Given: All pages of the project
When: User interacts with Button or Link
Then: The design should correspond to the new design from Figma https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?type=design&node-id=229-12512&t=NpmL9FmHrgq6g8Yi-0

### PR DESCRIPTION
**Pull request by Lykhoyda**
Closes #200

### CODE REVIEW

**Review by Tbaut — COMMENTED** [review]
Awesome, thanks for this. Here are some comments
- Can we have the font-size of buttons be 16px, this corresponds to the medium ones.
- let's use 2 buttons here, and fix the connect at the top-right. to test, you can use the deployment link, since it's a new domain, you won't be connected. You can also change the localStorage variable called `multix.canConnectToExtension` to `false`.
image

- the link icon isn't aligned properly
image

- it's not on the design yet, but discussed this with @sweetpea22 and I think it makes sense to have the back be secondary. As a rule of thumb I guess having 1 primary button per page is good.
image

- in Modals too, if we have 2 buttons, then the "back" should be secondary. The next/save/create should be primary.

**Comment by Lykhoyda** [comment]
> Awesome, thanks for this. Here are some comments
> 
> * Can we have the font-size of buttons be 16px, this corresponds to the medium ones.
> * let's use 2 buttons here, and fix the connect at the top-right. to test, you can use the deployment link, since it's a new domain, you won't be connected. You can also change the localStorage variable called `multix.canConnectToExtension` to `false`.
>   image
> * the link icon isn't aligned properly
>   image
> * it's not on the design yet, but discussed this with @sweetpea22 and I think it makes sense to have the back be secondary. As a rule of thumb I guess having 1 primary button per page is good.
>   image
> * in Modals too, if we have 2 buttons, then the "back" should be secondary. The next/save/create should be primary.

@Tbaut thank you for the review
1. button and connect fixed
2. Icon aligned
3. 'Back' changed to secondary

**Comment by Tbaut** [comment]
Thanks, there are a couple things still:
- I think you forgot that, can we have the font-size of buttons be 16px for buttons, this corresponds to the medium ones.
- When the modals have only 1 button, I guess it should be primary
- I saw in the "change multisig" modal has a back/save where both are still secondary
- The link icon is super far from the title, maybe we should have a padding-left of only .5rem
image

**Comment by Lykhoyda** [comment]
> Thanks, there are a couple things still:
> 
> * I think you forgot that, can we have the font-size of buttons be 16px for buttons, this corresponds to the medium ones.
> * When the modals have only 1 button, I guess it should be primary
> * I saw in the "change multisig" modal has a back/save where both are still secondary
> * The link icon is super far from the title, maybe we should have a padding-left of only .5rem
>   image

@Tbaut updated
regarding the "I saw in the "change multisig" modal has a back/save where both are still secondary", it could be a cache as it works on my side 
Screenshot 2023-06-09 at 12 04 46

**Review by Tbaut — APPROVED** [review]
Thanks a lot. 
I pushed some more nit fixing that were quicker to do than to comment about
- The approve button was still not primary (the reject was, but they never appear together)
- The buttons for batch extrinsics were too close together, added 1rem space. 
- The tx list was super close to the multisig list, not sure where this happened, certainly not this PR, anyway I added 1.5rem when on larger screens
image

**Pull request merged**
