### PR TITLE
update inputs styles

### LINKED ISSUE #165: Adapt inputs to the new design
Look for `<TextField` in the code, this is mostly for threshold and name input.
https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?type=design&node-id=229-12512&t=cYlBfIExNIk71DWG-0

image

### PR DESCRIPTION
**Pull request by Lykhoyda**
closes #165

### CODE REVIEW

**Comment by Lykhoyda** [comment]
@Tbaut please review. It might not cover all the input fields in the project, so please let me know if I miss something. The Selectors with Autocomplete will be tackled in the following story. Initially, I created the InputField component to have a simpler version, but if TextFiledStyled, which is the component from MUI, covers all our needs, we can keep only one.

**Comment by asnaith** [comment]
Hey @Lykhoyda, I took a look at this and like the new look! I just found a couple of niggly issues. 

It seems like the content is being indented quite a lot more than the design indicates? 

Examples: 

with accounts
Screenshot 2023-06-13 at 10 14 25 AM

with values
Screenshot 2023-06-13 at 10 49 22 AM

Another thing I found was that, when invoking an error, the input becomes vertically misaligned:

Examples: 

Screenshot 2023-06-13 at 10 25 07 AM


Screenshot 2023-06-13 at 10 26 31 AM

**Comment by Tbaut** [comment]
I'm just adding small things I saw while having a very quick look. I didn't check the code yet, but here's what I found
- Can we have the error color match the from the text? You can replace it in the theme already, if you search for `firebrick` so that it's changed across the board.
- Can we add some margin-top to the options in order not the list to overlap
image

**Comment by Lykhoyda** [comment]
@Tbaut @asnaith Thank you for the review! Please check the updated version

**Review by Tbaut — APPROVED** [review]
Awesome, thank you so much. I don't think this is something caused in this PR but I found some instances of the misalignment that Andrew mentioned. We can tackle that in a new issue if you prefer, up to you.

in the watched accounts
image

in the add account for a multisig:
image

and in the change multisig signatories
image

**Comment by asnaith** [comment]
@Lykhoyda @Tbaut I've created a separate issue for the input misalignment when an error message is invoked (https://github.com/ChainSafe/Multix/issues/211). Everything else is resolved and looks great so I think we should get this merged.

**Review by asnaith — APPROVED** [review]

**Pull request merged**
