### PR TITLE
Allow easy name edition

### PR DESCRIPTION
**Pull request by Tbaut**
closes #https://github.com/ChainSafe/Multix/issues/305

I ended up changing the icon because I found the single pencil as in the screenshot from the issue not clear enough when small. This one isn't as nice, but it's very clear IMHO.

---

Submission checklist:

#### Layout

- [x] Change inspected in the desktop web ui
- [x] Change inspected in the mobile web ui

#### Compatibility

- [x] Functionality of change validated with a connected account with multisig
- [x] Applicable elements hidden / disabled for watched multisigs / pure
- [x] Looks good for solo multisig
- [x] Looks good for multisig with proxy

### CODE REVIEW

**Comment by asnaith** [comment]
Fwiw I like the icon you went with more 😄

This is looking good for the most part but the implementation of it is a little weird on this screen, we only need one name field.

CleanShot 2024-03-27 at 10 20 30@2x

**Comment by Tbaut** [comment]
Thanks for the review. You can't simply change the name though if I remove the ability here. You would have to delete, then add the same account again with a name this time.

**Review by asnaith — APPROVED** [review]
@Tbaut ok If you're good with it then, just wanted to bring it to your attention. I see your point though

**Comment by Tbaut** [comment]
I originally didn't have it, and thought I'd it saves a couple clicks, I guess it doesn't hurt 🤷

**Pull request merged**
