### PR TITLE
Don't show old accounts when loading a new network

### PR DESCRIPTION
**Pull request by Tbaut**
closes https://github.com/ChainSafe/Multix/issues/308

### CODE REVIEW

**Comment by asnaith** [comment]
The multisigs / pures are being cleared and refreshed on network switch :) 

Just a few of issues:

- Re-direct to home when the network resolves is not working for me (the issue implies this should be happening).
- There's no loading / progress spinner shown on mobile view, desktop is fine
- Some nav links are being pushed underneath others

CleanShot 2023-08-28 at 13 18 30@2x

**Review by asnaith — CHANGES_REQUESTED** [review]
The multisigs / pures are being cleared and refreshed on network switch :) 

Just a few of issues:

- Re-direct to home when the network resolves is not working for me (the issue implies this should be happening).
- There's no loading / progress spinner shown on mobile view, desktop is fine
- Some nav links are being pushed underneath others
- Maybe another merge happened since this was submitted, there's now some component conflicts

CleanShot 2023-08-28 at 13 18 30@2x

**Comment by Tbaut** [comment]
Thanks, I have no idea how this happened, or how I couldn't have seen it. In any case I fixed it. The loader was white and hence invisible on mobile, that's definitely from me :+1: 

Regarding the redirect to home, it comes from me originally, but now I wonder if this is a good idea. I think we should ideally not do any magic and redirect without a good reason. wdyt?

**Review by asnaith — APPROVED** [review]
Nav links and a spinner on mobile all look good with the latest changes :) 

Also indifferent regarding the re-direction so let's leave it for now, we can revisit it in the future if we're more convinced that there's a need.

**Pull request merged**
