### PR TITLE
Safe number handling with BN

### LINKED ISSUE #49: Handle transfer of value with BN
Removes FIXME on https://github.com/ChainSafe/Multix/blob/108b17e9cd178166577e740c16d0d5b2e1a789ee/ui/src/components/EasySetup/BalancesTransfer.tsx#L48

### LINKED ISSUE #66: Wallet extension not presented when proposal is approved quickly
**Description**
The wallet extension will not be successfully called if you open a proposal and immediately click approve. 

It's a timing issue, if you wait a second or two longer it will work as intended. 

**Steps To Reproduce**

1. Open a signing proposal and click "approve" as fast you can

**Expected Behavior**
Wallet extension should be presented for signing

**Console Error**

 web3Enable: Enabled 1 extension: talisman/1.15.3 bundle.js:98:16

We donnot have the required data to submit the call react_devtools_backend.js:4012:25
    overrideMethod react_devtools_backend.js:4012
    onSign ProposalSigning.tsx:190
    onClick ProposalSigning.tsx:269
    React 32
    onOpenModal Transaction.tsx:35
    React 15

**Screenshots / Video**

https://user-images.githubusercontent.com/3982665/228360776-531e72e8-bb86-41c2-84f2-dd484237a0f6.mov

**Test Host Specifics: **
 - OS: macOS 13
 - Browser Firefox
 - Version 111

**Additional context**

- Happens with both Polkadot{.js} and Talisman extensions

### PR DESCRIPTION
**Pull request by Tbaut**
closes #49 
closes #66

### CODE REVIEW

**Comment by asnaith** [comment]
It's possible to bypass a lot of input validation on the send tx modal simply by entering valid text, removing it and then continuing with invalid input like 0.000000 or A, white space etc. 

You can also invoke the "Origin address balance too low" error but continue to enter and submit a larger amount. 

examples:

https://user-images.githubusercontent.com/3982665/228089866-15ca5fc4-80f7-4f17-aa54-6a124fb5b251.mov

**Comment by asnaith** [comment]
🟢 All test transactions look great to me, I verified in subscan that the exact value sent was as expected 👍

🟠 Input validation looks good now when trying to send more than balance, the "send" link becomes disabled. However, the link is now enabled by default now so clicking it without entering any input or by entering "ABC" is possible

**Comment by Tbaut** [comment]
Awesome, thanks a lot for the thorough tests. I'll fixed your comment.

**Comment by asnaith** [comment]
Working really well with the latest changes 🚀

I've created a separate issue from removing white space / non-numerical characters except `.` (https://github.com/ChainSafe/Multix/issues/68)

**Review by asnaith — APPROVED** [review]

**Pull request merged**
